# Generated by Django 4.0.3 on 2022-03-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.URLField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ', max_length=255),
            preserve_default=False,
        ),
    ]
